# download node 10.1.0 docker files
FROM node:latest

# switch docker dir to working dir
RUN mkdir -p /usr/app/waffletracker
WORKDIR /usr/app/waffletracker

# copy files
COPY package*.json /usr/app/waffletracker
COPY . /usr/app/waffletracker

# run install
RUN npm install -g typescript
RUN npm install -g webpack-dev-server webpack webpack-cli
RUN npm install

# make port exposed
EXPOSE 80

# run npm
CMD [ "npm", "run", "start:dev" ]