# download node 10.1.0 docker files
FROM node:latest

# switch docker dir to working dir
WORKDIR /usr/app

# copy files
COPY package*.json ./
COPY . .

# run install
RUN npm install
# RUN npm install -g nodemon
RUN npm install -g typescript

# make port exposed
EXPOSE 80

# run npm
CMD [ "npm", "run", "start:dev" ]