# download node 10.1.0 docker files
FROM node:latest

# switch docker dir to working dir
RUN mkdir -p /usr/app/waffletracker
WORKDIR /usr/app/waffletracker/

# run install
RUN npm install -g typescript ts-node
RUN npm install -g webpack-dev-server webpack webpack-cli

# copy package.json files and install
COPY package*.json /usr/app/waffletracker/
RUN npm install

# copy working files
COPY . /usr/app/waffletracker/

# make port exposed
EXPOSE 80

# run npm
CMD [ "npm", "run", "start:dev" ]